Fixed exception while processing missing file definitions.
While building ZACC documentation, exhale failed during parsing doxygen's XML files. Fixed by converting object to string.

Error message:

(!) Exception caught while parsing:Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/exhale/deploy.py", line 378, in explode
textRoot.parse()
File "/usr/local/lib/python3.6/site-packages/exhale/graph.py", line 979, in parse
self.discoverAllNodes()
File "/usr/local/lib/python3.6/site-packages/exhale/graph.py", line 1226, in discoverAllNodes
"{0}{1}".format(bullet, "\n{0}".format(bullet).join(c for c in candidates))
TypeError: sequence item 0: expected str instance, ExhaleNode found